#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Camera2Basic.Resource", IsApplication=true)]

namespace Camera2Basic
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int control_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070005
			public const int horizontal_page_margin = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int margin_huge = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int margin_large = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int margin_medium = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int margin_small = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int margin_tiny = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int vertical_page_margin = 2131165190;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_info = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int tile = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int container = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int control = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int info = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int picture = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int texture = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_camera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_camera2_basic = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int camera_error = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int description_info = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int intro_message = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int picture = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int request_permission = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int AppTheme = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int MaterialTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Base = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Theme_Sample = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int Widget = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Widget_SampleMessage = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Widget_SampleMessageTile = 2131099654;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
